version: "3.8"

services:
  backend:
    image: rafik609/task-manager_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tasks?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - app_network

  frontend:
    image: rafik609/task-manager_frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mysql:5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: overlay
